<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
<script>
    feather.replace();
</script>
<script src="/js/repairsearchvalidator.js"></script>
<script src="/js/create_owner_validator.js"></script>
<script type="module" src="/js/repairsearchvalidator.js"></script>
<script type="module" src="/js/validationOptions.js"></script>
<script type="module" src="/js/search-owner-validator.js"></script>
<script src="/js/datepicker.js"></script>
<script src="/js/repair_validator.js"></script>

